image: Visual Studio 2017

init:
# nothing here

install:
- choco install opencover.portable
- choco install codecov

before_build:
- dotnet restore

build_script:
- dotnet build

test_script:
- .scripts\TestCoverage.bat

after_test:
- codecov -f coverage-dotnet.xml
