version: 1.4.0.{build}

pull_requests:  
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

before_build:
- ps: >-
    
    (new-object net.webclient).DownloadFile('https://go.microsoft.com/fwlink/?LinkID=809122','core.exe')

    core.exe /install /quiet /norestart

    dotnet --version

build_script:  
- ps: .\Build.ps1

test: off