version: 1.4.0.{build}

pull_requests:  
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/4/6/1/46116DFF-29F9-4FF8-94BF-F9BE05BE263B/packages/DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe','core.exe')

    core.exe /install /quiet /norestart

build_script:  
- ps: .\Build.ps1

test: off