image: Visual Studio 2017

init:
# nothing here

install:
- choco install opencover.portable
- choco install codecov

before_build:
- dotnet restore

build_script:
- dotnet build

test_script:
- %VSINSTALLDIR%\Common7\IDE\Extensions\TestPlatform\vstest.console.exe .\SteamGaugesApi.Test\bin\Debug\netcoreapp2.0\SteamGaugesApi.Test.dll /collect:"Code Coverage"

after_test:
- codecov -f coverage-dotnet.xml
